<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3415b113caaeb2a851d8e767503a1ac7
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RedBeanPHP\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RedBeanPHP\\' => 
        array (
            0 => __DIR__ . '/..' . '/gabordemooij/redbean/RedBeanPHP',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3415b113caaeb2a851d8e767503a1ac7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3415b113caaeb2a851d8e767503a1ac7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3415b113caaeb2a851d8e767503a1ac7::$classMap;

        }, null, ClassLoader::class);
    }
}
