<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbc66a2a94abae2a39558ed5b7667ad77
{
    public static $prefixLengthsPsr4 = array (
        'R' =>
            array (
                'RedBeanPHP\\' => 11,
            ),
    );

    public static $prefixDirsPsr4 = array (
        'RedBeanPHP\\' =>
            array (
                0 => __DIR__ . '/PhpstormProjects' . '/gabordemooij/redbean/RedBeanPHP',
            ),
    );

    public static $classMap = array (
        'Composer\\web\\InstalledVersions' => __DIR__ . '/PhpstormProjects' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbc66a2a94abae2a39558ed5b7667ad77::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbc66a2a94abae2a39558ed5b7667ad77::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbc66a2a94abae2a39558ed5b7667ad77::$classMap;

        }, null, ClassLoader::class);
    }
}